### ISSUE TITLE
Can't install via command line

### ISSUE THREAD

**Issue by moejoee91** [TheFrankman/magento2-customhandles#3]
Hello,
Every time i try to install your module i get the error: 
the package can't be found in any version even though i make sure to specify the version : dev-master
Any idea what maybe causing the problem ?

**Comment by TheFrankman** [comment]
As far as I'm aware since it's a public repository you shouldn't have any issues. Here is what your composer.json should look like. I have just done a composer update on one of my sites without issue, however this could just be because i'm the owner.
```
"require": {
...
    "fc/custom_handles": "dev-master"
...
},
"repositories": {
...
    "fc/custom_handles": {
        "type": "vcs",
        "url": "git@github.com:TheFrankman/magento2-customhandles.git"
    },
...
}
```

Since you wish to use composer to install I have also just tag master at it's current state. You can now use `"fc/custom_handles": "1.0.0"`

**Comment by TheFrankman** [comment]
Since you haven't responded in 3 days i'm going to assume that this is resolved. Do let me know if you are still having issues installing and i'll help where i can.
